version: "3.9"
services:
  front:
    build:
      dockerfile: "Dockerfile"
      context: "."
    env_file:
      - docker-env
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/webroot:delegated
      - ./node_modules:/home/webroot/node_modules:cached
      # - ./webroot/node_modules:/home/webroot/node_modules:cached
      # - ./webroot:/home/webroot:ro
      # - ./webroot/public:/home/webroot/public:ro
      # - ./webroot/src:/home/src:ro
      # - ./webroot/build:/home/build:ro
      # - ./webroot/package.json:/home/package.json:ro
      # - ./webroot/package-lock.json:/home/package-lock.json:ro
      # - ./webroot/README.md:/home/README.md
    environment:
       - CHOKIDAR_USEPOLLING=true