version: "3.9"
services:
  server:
    build:
      dockerfile: "Dockerfile"
      context: "."
    env_file:
      - docker-env
    ports:
      - "3000:3000"
    volumes:
      - ./:/react/:delegated
      - /node_modules
    environment:
      - WATCHPACK_POLLING=true
